ClockInProject/ClockInProject/Controllers/CalendarController.cs
using ClockInProject.Models;
using ClockInProject.Service;
using ClockInProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace ClockInProject.Controllers
{  
    public class CalendarController : Controller
    {
        CalendarService calendarService = new CalendarService();
        ClockIn_Entity db = new ClockIn_Entity();
        const int page = 1;
        const int pageSize = 10;
        // GET: Calendar
        public ActionResult Index(CalendarIndexView calendarIndexView)
        {
            IEnumerable<SysUserCalendar> sysUserCalendars =
                db.SysUserCalendar.Where(x => x.UserID == User.Identity.Name).OrderBy(x=> x.AutoNo).ToPagedList(calendarIndexView.Page, calendarIndexView.PageSize);

            foreach (SysUserCalendar sysUserCalendar in sysUserCalendars)
            {
                sysUserCalendar.CalDate = sysUserCalendar.CalDate.Substring(0, 4) + "/" + sysUserCalendar.CalDate.Substring(4, 2) + "/" + sysUserCalendar.CalDate.Substring(6, 2);
            }

            return View(sysUserCalendars);
        }

        [HttpPost]
        public ActionResult Index(string CalDate_Start, string CalDate_End)
        {
            IEnumerable<SysUserCalendar> sysUserCalendars =
                db.SysUserCalendar.Where(x => x.UserID == User.Identity.Name && 
                (x.CalDate.CompareTo(CalDate_Start.Replace("-", "")) >= 0 &&
                x.CalDate.CompareTo(CalDate_End.Replace("-", "")) < 0)
                ).OrderBy(x => x.AutoNo).ToPagedList(page, pageSize);

            foreach (SysUserCalendar sysUserCalendar in sysUserCalendars) 
                sysUserCalendar.CalDate = sysUserCalendar.CalDate.Substring(0, 4) + "/" + sysUserCalendar.CalDate.Substring(4, 2) + "/" + sysUserCalendar.CalDate.Substring(6, 2);
            

            return View(sysUserCalendars);
        }

        [HttpPost]
        public ActionResult New(CalendarIndexView calendarIndexView)
        {

            return View();
        }

        public ActionResult New()
        {
            return View();
        }
    }
}

ClockInProject/ClockInProject/Controllers/ExcelController.cs
using ClockInProject.Models;
using ClockInProject.Service;
using ClockInProject.ViewModels;
using System.IO;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using System.Linq;
using System.Data;
using System.Collections.Generic;

namespace ClockInProject.Controllers
{
    public class ExcelController : Controller
    {
        ExcelService excelService = new ExcelService();
        ClockIn_Entity db = new ClockIn_Entity();
        // GET: Excel 
        public ActionResult Index()
        { 
            ViewBag.TableItems = excelService.GetTableName();
             
            return View();
        }

        [HttpPost]
        public ActionResult Index(ExcelIndexView excelIndexView)
        {
            if (ModelState.IsValid)
            {
                excelIndexView.LstDr = new List<DataRow>();

                if (excelIndexView.RdnList1 == "Export")
                {
                    //匯出
                     
                    excelIndexView.dataTable = excelService.RenderDataTableToExcel(excelIndexView.DrpTableName, "D:\\" + excelIndexView.DrpTableName + ".xls");
                    
                }
                else
                {

                    //string path = Path.Combine(Server.MapPath($"~/Images"), excelIndexView.fileupload.FileName);
                    //匯入
                    excelIndexView.dataTable = excelService.RenderExcelToDataTable(excelIndexView.DrpTableName, "D:\\" + excelIndexView.DrpTableName + ".xls");
                    excelService.UpdateToDatabase(excelIndexView.dataTable);
                    
 
                            

                            
                    
                            
                           
                }

                foreach (DataRow item in excelIndexView.dataTable.Rows)
                    excelIndexView.LstDr.Add(item);

                excelIndexView.PagLstDr = new PagedList<DataRow>(excelIndexView.LstDr, excelIndexView.Page, excelIndexView.PageSize);
            }

            ViewBag.TableItems = excelService.GetTableName();

            return View(excelIndexView);
        }
    }
}

ClockInProject/ClockInProject/Controllers/StockController.cs
using ClockInProject.Models;
using ClockInProject.Service;
using ClockInProject.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ClockInProject.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        private string StrBaseurl = "https://openapi.twse.com.tw/v1/exchangeReport/BWIBBU_ALL";
        StockService stockService = new StockService();

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Login");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(string Code)
        {
            //SSL/TLS通道開啟
            ServicePointManager.ServerCertificateValidationCallback += (s, cert, chain, sslPolicyErrors) => true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            StockIndexView stockIndexView = new StockIndexView();

            using (var client = new HttpClient())
            {
                //初始化
                //client.BaseAddress = new Uri(StrBaseurl);
                //client.DefaultRequestHeaders.Clear();
                //client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(StrBaseurl);

                //讀取成功  
                if (Res.IsSuccessStatusCode)
                {
                    //API結果篩進LIST   
                    var StockResponse = Res.Content.ReadAsStringAsync().Result;
                    stockIndexView = JsonConvert.DeserializeObject<List<StockIndexView>>(StockResponse).Where(x => x.Code == Code).FirstOrDefault();

                }

            }



            //Dictionary<int, string> categorys = stockService.GetAll();
            //List<SelectListItem> LstItems = new List<SelectListItem>();
            //foreach (KeyValuePair<int, string> item in categorys)
            //{
            //    LstItems.Add(new SelectListItem()
            //    {
            //        Text = item.Value,
            //        Value = item.Key.ToString()
            //    });
            //}

            //ViewBag.categorys = LstItems;
            return PartialView("PartialView/_PartialIndex", stockIndexView);
        }


    }
}

ClockInProject/ClockInProject/Views/Shared/_Layout.cshtml
 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>KS系統| @ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/Views/Shared/_Layout.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">  
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")" type="text/javascript"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="/js/datatables-simple-demo.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    @*<script>
             $(function () {
                $.ajax({
                    method: "GET",
                    url: "https://localhost:44312/Service1.svc/Tutorial/PK",
                    contentType: "application/json",
                    dataType: "json",
                    success: function (data) {
                        const myJSON = JSON.stringify(data);
                        let obj = JSON.parse(myJSON, (key, value) => {
                            //key是欄位名稱
                            if (key == "MsgTitle") {
                                alert(value);
                            }

                        });
                    }
                });
            });
        </script>*@

</head>
<body class="sb-nav-fixed">
    @* 最上面那列 *@
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        @* 首頁 *@
        <a class="navbar-brand ps-3" href="index.html">KS</a>
        @* 開關左邊選單 *@
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
         
        @* 搜尋欄 *@
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            @if (User.Identity.IsAuthenticated)
            {

                <span style="color:white;">
                    歡迎 @Html.Encode(User.Identity.Name)
                </span>
            }

            @*<div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>*@
        </form>
        @* 右上角人員登出按鈕 *@
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <!--<li><hr class="dropdown-divider" /></li>--->
                    <li>@Html.ActionLink("登出", "Logout", "Login", new { }, new { @class = "dropdown-item" })</li>

                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        @* 左邊列表 *@
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                @* 列表Body *@
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">功能列表</div>
                        <a class="nav-link" href="@Url.Action("Index","Calendar")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            行事曆
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Stock")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            股票資訊
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Excel")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Excel匯入匯出
                        </a>

                    </div>
                </div>
                @* 列表footer *@
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                </div>
            </nav>
        </div>
        @* 底下頁面 *@
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @if(!(ViewContext.RouteData.Values["controller"].ToString() == "Home" &&
                        ViewContext.RouteData.Values["action"].ToString() == "Index"))
                     { 
                        <p>目前位置：@Html.MvcSiteMap().SiteMapPath()</p>
                     }
                    @RenderBody()

                </div>
            </main>
            @* 頁腳 *@
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; KS 2021</div>
                        <div>
                            <a href="#">KS IS BEST</a>
                            &middot;
                            <a href="#"></a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
</body>
</html>

ClockInProject/ClockInProject/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <link href="~/Views/Shared/_LayoutLogin.css" rel="stylesheet" />
    <title>KS系統| @Page.Title</title>
    
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-login">
                    <div class="row">
                        <div class="text-center">
                            <img src="~/Images/logo.png" style="width:25%" />
                            </div>
                        </div>
                        <div id="LoginOrRegister" class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="@Url.Action("Index", "Login")" id="login-form-link">登入</a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="@Url.Action("Register", "Login")" id="register-form-link">註冊</a>
                                </div>
                            </div>
                            <hr>
                        </div>
                        @RenderBody()
                    </div>
                </div>
        </div>
    </div>
</body>
</html>